version: "3.8"

services:
  app: # 1st service
    image: toxic-classifier
    container_name: mtoxic-classifier-app # Also used as hostname
    build:
      context: ./
      dockerfile: docker/Dockerfile
    # env_file: # Location of file(s) containing the env vars. Only accessed by the container.
      # - ./.envs/.postgres
    # volumes: # Persist the data volume
      # - postgresql-data:/var/lib/postgresql/data
